using Autofac;
using Autofac.Extensions.DependencyInjection;
using chessAPI;
using chessAPI.business.interfaces;
using chessAPI.models.player;
using Microsoft.AspNetCore.Authorization;
using Serilog;
using Serilog.Events;
using chessAPI.dataAccess.providers.postgreSQL;

//Serilog logger (https://github.com/serilog/serilog-aspnetcore)
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateBootstrapLogger();

try
{
    Log.Information("chessAPI starting");
    var builder = WebApplication.CreateBuilder(args);

    var connectionStrings = new connectionStrings();
    builder.Services.AddOptions();
    builder.Services.Configure<connectionStrings>(builder.Configuration.GetSection("ConnectionStrings"));
    builder.Configuration.GetSection("ConnectionStrings").Bind(connectionStrings);

    // Two-stage initialization (https://github.com/serilog/serilog-aspnetcore)
    builder.Host.UseSerilog((context, services, configuration) => configuration.ReadFrom
             .Configuration(context.Configuration)
             .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning).ReadFrom
             .Services(services).Enrich
             .FromLogContext().WriteTo
             .Console());

    // Autofac como inyección de dependencias
    builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
    builder.Host.ConfigureContainer<ContainerBuilder>(builder => builder.RegisterModule(new chessAPI.dependencyInjection<int, int>()));
    var app = builder.Build();
    app.UseSerilogRequestLogging();
    app.UseMiddleware(typeof(chessAPI.customMiddleware<int>));
    app.MapGet("/", () =>
    {
        return "hola mundo";
    });

    app.MapGet("/getplayers", () =>
    {
        Conexion jugadores = new Conexion();
        return jugadores.ExecuteQuery("select * from player");
    });

    app.MapGet("/getgames", () =>
    {
        Conexion juegos = new Conexion();
        return juegos.ReadGames("select * from game");
    });

    app.MapPost("/player", (clsNewPlayer newPlayer)=> {
        var query = "CREATE TABLE IF NOT EXISTS player(id_player int primary key generated by default as identity,email varchar(50) not null);" +                             
                    "INSERT INTO player (email) values('@email');";
        var exquery = query.Replace("@email",newPlayer.email);            
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(exquery);
    });

    app.MapPost("/game", (clsNewGame newGame)=> {
        var query = "CREATE TABLE IF NOT EXISTS game (id_game int generated by default as identity,firstplayerscore int,secondplayerscore int,id_firstplayer int,id_secondplayer int, constraint fk_gamefp foreign key (id_firstplayer) references player(id_player),constraint fk_gamesp foreign key (id_secondplayer) references player(id_player));" +                             
                    "insert into game(firstplayerscore,secondplayerscore,id_firstplayer,id_secondplayer) values (0,0,@id1,@id2);";
        var exquery = query.Replace("@id1",Convert.ToString(newGame.id_firstplayer)); 
        exquery = exquery.Replace("@id2",Convert.ToString(newGame.id_secondplayer));            
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(exquery);
    });

    app.MapPut("/updateplayer",(clsPlayer<int> Player) => {
         var query = "update player set email = '@email' where id_player = @id;";
        var exquery = query.Replace("@email",Player.email);
        exquery = exquery.Replace("@id",Convert.ToString(Player.id));            
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(exquery);
    });

    app.MapPut("/updategame",(clsGame game) => {
         var query = "update game set firstplayerscore = @fs, secondplayerscore = @ss where id_game = @id;";
        var exquery = query.Replace("@fs",Convert.ToString(game.firstplayerscore));
        exquery = exquery.Replace("@ss",Convert.ToString(game.secondplayerscore));
        exquery = exquery.Replace("@id",Convert.ToString(game.id));    
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(exquery);
    });

    

    //app.MapPost("player", 
    //[AllowAnonymous] async(IPlayerBusiness<int> bs, clsNewPlayer newPlayer) => Results.Ok(await bs.addPlayer(newPlayer)));

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "chessAPI terminated unexpectedly");
}
finally
{
    Log.CloseAndFlush();
}
