using Autofac;
using Autofac.Extensions.DependencyInjection;
using chessAPI;
using chessAPI.business.interfaces;
using chessAPI.models.player;
using Microsoft.AspNetCore.Authorization;
using Serilog;
using Serilog.Events;
using chessAPI.dataAccess.providers.postgreSQL;
using Microsoft.EntityFrameworkCore;
using chessAPI.models;

//Serilog logger (https://github.com/serilog/serilog-aspnetcore)
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateBootstrapLogger();

try
{
    Log.Information("chessAPI starting");
    var builder = WebApplication.CreateBuilder(args);

    var connectionStrings = new connectionStrings();
    builder.Services.AddOptions();
    builder.Services.Configure<connectionStrings>(builder.Configuration.GetSection("ConnectionStrings"));
    builder.Configuration.GetSection("ConnectionStrings").Bind(connectionStrings);

    // Two-stage initialization (https://github.com/serilog/serilog-aspnetcore)
    builder.Host.UseSerilog((context, services, configuration) => configuration.ReadFrom
             .Configuration(context.Configuration)
             .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning).ReadFrom
             .Services(services).Enrich
             .FromLogContext().WriteTo
             .Console());

    // Autofac como inyección de dependencias
    builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
    builder.Host.ConfigureContainer<ContainerBuilder>(builder => builder.RegisterModule(new chessAPI.dependencyInjection<int, int>()));
    var app = builder.Build();
    app.UseSerilogRequestLogging();
    app.UseMiddleware(typeof(chessAPI.customMiddleware<int>));
    app.MapGet("/", () =>
    {
        return "hola mundo";
    });

    app.MapGet("/getplayers", () =>
    {
        Conexion jugadores = new Conexion();
        return jugadores.ReadPlayers("select * from player");
    });

    app.MapGet("/getgames", () =>
    {
        Conexion juegos = new Conexion();
        return juegos.ReadGames("select * from game");
    });

    app.MapPost("/player", (clsNewPlayer newPlayer)=> {
        var query = "CREATE TABLE IF NOT EXISTS player(id_player int primary key generated by default as identity,email varchar(50) not null);" +                             
                    "INSERT INTO player (email) values('@email');";
        var exquery = query.Replace("@email",newPlayer.email);            
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(exquery);
    });

    app.MapPost("/game", (clsNewGame newGame) =>
    {
        var query = "INSERT INTO public.game(started, whites, blacks, turn, winner)VALUES (NOW(), @whites, @blacks, @turn, @winner);";
        query = query.Replace("@whites", Convert.ToString(newGame.whites));
        query = query.Replace("@blacks", Convert.ToString(newGame.blacks));
        query = query.Replace("@turn", Convert.ToString(newGame.turn));
        query = query.Replace("@winner", Convert.ToString(newGame.winner));

        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(query);
    });

    app.MapPut("/updateplayer",(clsPlayer<int> Player) => {
         var query = "update player set email = '@email' where id = @id;";
        var exquery = query.Replace("@email",Player.email);
        exquery = exquery.Replace("@id",Convert.ToString(Player.id));            
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(exquery);
    });

    app.MapPut("/updategame", (clsGame game) =>
    {
        var query = "UPDATE public.game SET whites=@whites, blacks=@blacks, turn=@turn, winner=@winner WHERE id=@id;";
        query = query.Replace("@whites", Convert.ToString(game.whites));
        query = query.Replace("@blacks", Convert.ToString(game.blacks));
        query = query.Replace("@turn", Convert.ToString(game.turn));
        query = query.Replace("@winner", Convert.ToString(game.winner));
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(query);
    });


    app.MapPost("/game", (clsNewGame newGame) =>
    {
        var query = "INSERT INTO public.game(started, whites, blacks, turn, winner)VALUES (NOW(), @whites, @blacks, @turn, @winner);";
        query = query.Replace("@whites", Convert.ToString(newGame.whites));
        query = query.Replace("@blacks", Convert.ToString(newGame.blacks));
        query = query.Replace("@turn", Convert.ToString(newGame.turn));
        query = query.Replace("@winner", Convert.ToString(newGame.winner));

        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(query);
    });



    app.MapPut("/unirsepartida", (team_player game) =>
    {
        var query = "INSERT INTO public.team_player(team_id, player_id) VALUES (@teamid ,@playerid );";
        query = query.Replace("@teamid", Convert.ToString(game.team_id));
        query = query.Replace("@playerid", Convert.ToString(game.player_id));
        Conexion jugador = new Conexion();
        jugador.ExecuteNonQuery(query);
    });


    //app.MapPost("player", 
    //[AllowAnonymous] async(IPlayerBusiness<int> bs, clsNewPlayer newPlayer) => Results.Ok(await bs.addPlayer(newPlayer)));

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "chessAPI terminated unexpectedly");
}
finally
{
    Log.CloseAndFlush();
}
